name: vitas
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.46.3=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.1.0
      - ale-py==0.8.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.4.1
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==7.1.2
      - cloudpickle==3.0.0
      - conda-pack==0.8.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.10
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.7.0
      - etils==1.7.0
      - evdev==1.7.1
      - exceptiongroup==1.1.3
      - executing==2.1.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.13.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - ftfy==6.1.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - glfw==2.6.5
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - gymnasium-robotics==1.2.3
      - h5py==3.11.0
      - hidapi==0.14.0
      - huggingface-hub==0.19.3
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.1.5
      - idna==3.4
      - imageio==2.29.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==4.13.0
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - iopath==0.1.10
      - ipython==8.27.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.1
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - llvmlite==0.43.0
      - loguru==0.7.2
      - lxml==5.2.2
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - mujoco==3.1.2
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pandas==2.1.3
      - parso==0.8.4
      - pettingzoo==1.24.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - pip-date==1.0.5
      - platformdirs==4.2.2
      - pluggy==1.3.0
      - portalocker==2.8.2
      - positional-encodings==6.0.1
      - proglog==0.1.10
      - prompt-toolkit==3.0.47
      - protobuf==4.23.4
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.22
      - pygame==2.6.0
      - pygments==2.18.0
      - pyminitouch==0.3.3
      - pynput==1.7.7
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - python-xlib==0.33
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - req2toml==1.2.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.1
      - robosuite==1.4.1
      - rsa==4.9
      - safetensors==0.4.0
      - scipy==1.14.0
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - shimmy==1.3.0
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - some-package==0.1
      - stable-baselines3==2.3.2
      - stack-data==0.6.3
      - submitit==1.5.2
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - timm==0.9.10
      - tomli==2.0.1
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tyro==0.8.4
      - tzdata==2023.3
      - urllib3==2.1.0
      - vit-pytorch==1.6.4
      - wandb==0.16.0
      - wcwidth==0.2.10
      - werkzeug==3.0.1
      - zipp==3.17.0
